[package]
name = "matrix_mozilla_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = "^0.13"
matrix-sdk="^0.6"
reqwest = "^0.11"
scraper = "^0.14"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "^0.3"
