[login]
username = "username"
password = "password"
homeserver_url = "https://chat.example.com"
# Optional. Defaults to true
# persist_storage = true
# Optional. Defaults to $XDG_DATA_DIR/matrix_mozilla_bot/session,
# or ./matrix_mozilla_bot/session on weird platforms where `dirs` can't find a data-dir
# db_path = "/somewhere/far/away"
# Optional. You get prompted on startup, if this is omitted.
# db_pw = "something very secret"
# Optional. Defaults to true. If this is set to true, session_path is ignored.
# use_secret_service = false
# Optional. Default to db_path/session.dump
# NOTE: This is very insecure, as your session-token gets saved plain-text
# session_path = "/somewhere/more/secretive/"

[config]
ignore_own_messages = true
autojoin = true
accept_commands_from = ["@alice:alice.com", "@bob:bob.org"]

[subscription.ff_cand]
url_part="firefox/candidates"
# Only watch versions >=100 as we are not interested in anything older
filter="1[0-9][0-9].*"
query_subdirs= true 

[subscription.ff_rel]
url_part="firefox/releases"
query_subdirs= false

[subscription.tb_cand]
url_part="thunderbird/candidates"
filter="1[0-9][0-9].*"
query_subdirs= true

[subscription.tb_rel]
url_part="thunderbird/releases"
query_subdirs= false

[subscription.nss_rel]
url_part="security/nss/releases"
query_subdirs= false
